version: '2'
services:
  messagebus:
    container_name: knapsack-message-bus
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    container_name: knapsack-db
    image: mysql:5
    user: "1000:50"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d/:ro
  api:
    build: ./knapsack-api
    container_name: knapsack-api
    volumes:
      - ./knapsack-api/target/scala-2.12:/app
    ports:
      - "5000:5000"
  engine:
    build: ./knapsack-deap
    container_name: knapsack-engine
    volumes:
      - ./knapsack-deap:/code
